import { StyleSheet } from 'react-native';

import { agentTheme } from '../../constants/agentTheme';
import { AVATAR_COLOR, BORDER_COLOR, CARD_BACKGROUND, DIVIDER_COLOR, SHEET_BACKGROUND, serifFont } from './meSheetData';

export const styles = StyleSheet.create({
  root: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 90,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#111111',
  },
  sheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: '86%',
    paddingTop: 14,
    paddingHorizontal: 30,
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    backgroundColor: SHEET_BACKGROUND,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    elevation: 20,
  },
  creditsSheet: {
    paddingHorizontal: 25,
  },
  dragHandle: {
    alignSelf: 'center',
    width: 41,
    height: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(31,36,48,0.2)',
  },
  headerArea: {
    alignItems: 'center',
    paddingTop: 28,
    paddingBottom: 21,
  },
  avatar: {
    width: 76,
    height: 76,
    borderRadius: 38,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: AVATAR_COLOR,
  },
  avatarText: {
    color: '#fff',
    fontSize: 29,
    lineHeight: 34,
    fontWeight: '600',
    letterSpacing: -0.35,
  },
  name: {
    maxWidth: '88%',
    marginTop: 15,
    color: agentTheme.colors.text,
    fontFamily: serifFont,
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '700',
    letterSpacing: -0.5,
    textAlign: 'center',
  },
  subtitle: {
    marginTop: 1,
    color: agentTheme.colors.mutedText,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '400',
    letterSpacing: -0.12,
  },
  card: {
    overflow: 'hidden',
    borderRadius: 19,
    backgroundColor: CARD_BACKGROUND,
    borderWidth: 1,
    borderColor: BORDER_COLOR,
  },
  row: {
    minHeight: 49,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 18,
    paddingRight: 15,
  },
  iconSlot: {
    width: 31,
    alignItems: 'flex-start',
    justifyContent: 'center',
    marginRight: 12,
  },
  rowLabel: {
    color: agentTheme.colors.text,
    fontSize: 13.6,
    lineHeight: 17,
    fontWeight: '700',
    letterSpacing: -0.12,
  },
  rowLabelWithValue: {
    width: 82,
  },
  rowLabelAction: {
    flex: 1,
  },
  rowValue: {
    color: 'rgba(31,36,48,0.74)',
    flex: 1,
    marginRight: 9,
    textAlign: 'right',
    fontSize: 13.6,
    lineHeight: 17,
    fontWeight: '400',
    letterSpacing: -0.1,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    marginLeft: 61,
    backgroundColor: DIVIDER_COLOR,
  },
  sectionLabel: {
    color: agentTheme.colors.mutedText,
    marginTop: 22,
    marginLeft: 18,
    marginBottom: 13,
    fontSize: 10.5,
    lineHeight: 14,
    fontWeight: '800',
    letterSpacing: 4,
  },
  creditsContent: {
    flex: 1,
  },
  creditsHeader: {
    height: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
  creditsCloseButton: {
    position: 'absolute',
    left: 0,
    width: 44,
    height: 44,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  creditsTitle: {
    color: agentTheme.colors.text,
    fontFamily: serifFont,
    fontSize: 29,
    lineHeight: 36,
    fontWeight: '700',
    letterSpacing: -0.45,
    textAlign: 'center',
  },
  creditsScrollContent: {
    paddingBottom: 28,
  },
  creditsCard: {
    paddingHorizontal: 40,
    paddingTop: 24,
    paddingBottom: 18,
    borderRadius: 22,
    backgroundColor: CARD_BACKGROUND,
    borderWidth: 1,
    borderColor: BORDER_COLOR,
  },
  creditsPlanHeader: {
    minHeight: 60,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  creditsPlanTitle: {
    color: agentTheme.colors.text,
    fontFamily: serifFont,
    fontSize: 29,
    lineHeight: 36,
    fontWeight: '700',
    letterSpacing: -0.45,
  },
  upgradeButton: {
    minWidth: 116,
    height: 49,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: agentTheme.colors.text,
  },
  upgradeButtonText: {
    color: '#fff',
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '600',
    letterSpacing: -0.22,
  },
  creditsWideDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: 'rgba(31,36,48,0.1)',
  },
  creditMetricRow: {
    minHeight: 78,
    flexDirection: 'row',
    alignItems: 'center',
  },
  creditMetricIconSlot: {
    width: 34,
    alignItems: 'flex-start',
    justifyContent: 'center',
    marginRight: 28,
  },
  creditMetricTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  creditMetricLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  creditMetricLabel: {
    color: agentTheme.colors.text,
    flexShrink: 1,
    fontFamily: serifFont,
    fontSize: 20.5,
    lineHeight: 25,
    fontWeight: '600',
    letterSpacing: -0.22,
  },
  creditMetricSubtitle: {
    marginTop: 4,
    color: agentTheme.colors.mutedText,
    fontFamily: serifFont,
    fontSize: 15.5,
    lineHeight: 20,
    fontWeight: '400',
    letterSpacing: -0.1,
  },
  creditMetricValue: {
    color: agentTheme.colors.text,
    minWidth: 48,
    marginLeft: 10,
    textAlign: 'right',
    fontFamily: serifFont,
    fontSize: 21,
    lineHeight: 26,
    fontWeight: '500',
    letterSpacing: -0.22,
  },
  historyGroup: {
    marginTop: 28,
  },
  historyDate: {
    color: agentTheme.colors.mutedText,
    marginLeft: 4,
    marginBottom: 14,
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '700',
    letterSpacing: 2.4,
  },
  historyItem: {
    minHeight: 55,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    paddingLeft: 17,
    paddingRight: 18,
    backgroundColor: CARD_BACKGROUND,
    borderWidth: 1,
    borderColor: BORDER_COLOR,
  },
  historyTitle: {
    color: agentTheme.colors.text,
    flex: 1,
    marginRight: 12,
    fontFamily: serifFont,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '400',
    letterSpacing: -0.2,
  },
  historyValue: {
    color: 'rgba(31,36,48,0.66)',
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '500',
    letterSpacing: -0.18,
  },
  pressed: {
    opacity: 0.58,
  },
});
